#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <omp.h>

void mandelbrot(double zreal, double zimag){
	int i, niter = 500000, threshold = 4;
	double temp, zabs, x = 0, y = 0;

	for (i = 0; i < niter; i++){
		temp = x;
		x = (x*x) - (y*y) + zreal;
		y = (2*temp*y) + zimag;
		zabs = (x*x) + (y*y);
		if (zabs > threshold){
			#pragma omp ordered
			printf(" ");
			return;
		}
	}
	#pragma omp ordered
	printf(".");
	return;
}


int main(){
	int a, b, n = 80, m = 50;
	double zreal, zimag;
	double zimag_start = -1, zimag_end = 1;
	double zreal_start = -2, zreal_end = 1;

	double zimag_middle = (fabs(zimag_start) + fabs(zimag_end))/m;
 	double zreal_middle = (fabs(zreal_start) + fabs(zreal_end))/n;

 	// start timer
	double start_time, end_time;
	start_time = omp_get_wtime();

	// set number of threads
	omp_set_dynamic(0);
	omp_set_num_threads(4);
	
	for (a = 0; a <= m; a++){
		zimag = zimag_start + zimag_middle*a;

		#pragma omp parallel for ordered schedule(dynamic)
		for (b = 0; b <= n; b++){
			zreal = zreal_start + zreal_middle*b;
			mandelbrot(zreal, zimag);
		}
		printf("\n");
	}
	
	// end timer
	end_time = omp_get_wtime();
	printf("Total execution time: %.2lf\n", end_time - start_time);
	
	return 0;
}


/*
Notes:
 - parallelization makes code only slightly faster
 - for 8 threads: 2.50s -> 2.34s (-O3)

Output: 
                                                  .

                                                .....
                                                .....
                                                .....
                                                 ...
                                                ......
                                       ..   .............
                                       .. ................. ...
                                         .....................
                                       ......................
                                    ..........................
                                     ..........................
                                     ..........................
                                    ............................
                                   .............................
                       . ....      .............................
                       .........   .............................
                     ...........  ..............................
                     ............ .............................
                     ............ .............................
                  .. .........................................
.............................................................
                  .. .........................................
                     ............ .............................
                     ............ .............................
                     ...........  ..............................
                       .........   .............................
                       . ....      .............................
                                   .............................
                                    ............................
                                     ..........................
                                     ..........................
                                    ..........................
                                       ......................
                                         .....................
                                       .. ................. ...
                                       ..   .............
                                                ......
                                                 ...
                                                .....
                                                .....
                                                .....

                                                  .

*/